puddle/conversation/urls.py
from django.urls import path

from .views import new_conversation, inbox, detail

app_name = "conversation"

urlpatterns = [
    path('new/<int:item_pk>/', new_conversation, name="new"),
    path('inbox/', inbox, name="inbox"),
    path('<int:pk>/', detail, name="detail"),
]

puddle/core/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views 
from . import views
from .forms import LoginForm
app_name = 'core'

urlpatterns = [
    path('',views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    #using django's login view
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout')
]

puddle/dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
    path('', views.index, name= 'index'),
]

puddle/item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

puddle/puddle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('conversation/', include('conversation.urls')),
    
    
   
] 


urlpatterns +=   static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

puddle/core/models.py
from django.db import models

# Create your models here.

puddle/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your email',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
        
class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': 'w-full py-4 px-6 rounded-xl'
        }))

puddle/core/views.py
from django.shortcuts import render,redirect
from item.models import Category, Item
from .forms import SignupForm
from django.contrib.auth import logout

# Create your views here.
def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    context = {
        'items': items,
        'categories': categories,
    }
    return render(request, 'core/index.html',context) 

def contact(request):

    return render(request, 'core/contact.html')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()

    context = {
        'form': form,
    }
    return render(request, 'core/signup.html', context)

def logout_view(request):
    logout(request)
    return redirect('/') # replace 'home' with the name of your homepage URL

puddle/core/templates/core/base.html
<!DOCTYPE html>
    <head>
        <meta charset="utf-8">  
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <script src="https://cdn.tailwindcss.com"></script>

       <title> {% block title %}{% endblock %} | Puddle</title>
    
    <body>
        <!--navbar-->
        <nav class= "py-6 px-6 flex justify-between items-center border-b border-gray-200 bg-blue-100">

            <a href="/" class="text-xl font-semibold">Puddle</a>

            {% if request.user.is_authenticated %}
            <div>Welcome {{request.user}}</div>
            {% endif %}

            <div class= "space-x-6">
                <!--If user not logged in (default)-->
                <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New item</a>
                <a href="/" class="text-lg font-semibold hover:text-gray-500">Browse</a>
                <!-- If user is logged in -->
                {% if request.user.is_authenticated %}

                
                <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
                <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-red-300">Log out</a>
                {% else %}
                <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a>
                {% endif %}
            </div>

        </nav>

        <!--Content of the page after navbar-->
        <div class="px-6 py-6">
            {% block content %}{% endblock %}
        </div>
        
        <!--Footer-->
        <footer class= " py-6 px-6 flex justify-between bg-gray-800">
            <div class= "w-2/3 pr-10">
                <h3 class=" mb-5 font-semibold text-gray-400">About</h3>
                <p class= "text-lg text-gray-500">blah blah blah</p>
            </div>

            <div class="w-1/3">
                <h3 class=" mb-5 font-semibold text-gray-400">About</h3>
                <ul class= "space-y-2">
                    <li><a href="#" class= "text-lg text-teal-500 hover:text-teal-700">About</li>
                    <li><a href="{% url 'core:contact' %}" class= "text-lg text-teal-500 hover:text-teal-700">Contact</li>
                    <li><a href="#" class= "text-lg text-teal-500 hover:text-teal-700">Privacy Policy</li>
                    <li><a href="#" class= "text-lg text-teal-500 hover:text-teal-700">Terms of use</li>
                </ul>
            </div>

            
        </footer>
    </body>
</html>

puddle/core/templates/core/contact.html
{% extends "core/base.html" %}

{%block title%}Contact{%endblock%}
{% block  content %}<h1>Contact page</h1>{% endblock %} 

puddle/core/templates/core/index.html
{% extends "core/base.html" %}

{%block title%}Welcome{%endblock%}
{% block  content %}
<!--content block div-->
<div class = "mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Newest items</h2>
    <!--display Newest unsold items-->
    <div class = "grid grid-cols-3 gap-3">
    {%for item in items%}
        <div>
            <a href="{% url 'item:detail' item.id %}">
                <div> <img src="{{item.image.url}}" class = "rounded-xl"> </div>
            </a>  
    <!--Display name and price of item-->
    <div class="p-6 bg-gray-200 rounded-b-xl"> 
        <h2 class= "text-2xl">{{item.name}}</h2>
        <p class= "text-gray-500">Price:{{item.price}}</p> 
    </div>
</div>
    {%endfor%}
    </div>
</div>
<!--To display categories-->
<div class = "mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Categories</h2>

    <!--Display category names and its count-->
    <div class = "grid grid-cols-3 gap-3">
        {%for category in categories%}
    <div class="p-6 bg-black-700 rounded-b-xl"> 
        <h2 class= "text-2xl">{{category.name}}</h2>
        <p class= "text-gray-500">{{category.items.count}} items</p> 
    </div>

        {%endfor%}
    </div>
</div>
{% endblock %} 

puddle/core/templates/core/login.html
{% extends 'core/base.html' %}
{% block title %}Log in page{% endblock%}  

{% block content %}
    <div class= "w-1/2 my-6 mx-auto bg-gray-100 rounded-xl px-3 ">
        <h1 class="mb-6 p-6 text-3xl">Login </h1>

        <form method="post" action=".">
            <!--django in-built security feature-->
            {% csrf_token %}
            <!--render the form-->
            
            <div class="mb-3">
                <label class="inline-block mb-2">Username:</label><br>{{ form.username}}<br>
                
                <label class="inline-block mb-2">Enter password:</label><br>{{ form.password}}<br>
                
            </div>
            <!--handle errors-->
            {% if form.errors or form.non_field_errors %}
                <div class= "mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{form.non_field_errors}}
                </div>
            {% endif %}
            
            <!--submit button-->
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Login</form>

        </form>
    </div>
{%endblock%}

puddle/core/templates/core/signup.html
{% extends 'core/base.html' %}
{% block title %}Sign Up page{% endblock%}  

{% block content %}
    <div class= "w-1/2 my-6 mx-auto bg-gray-100 rounded-xl px-3 ">
        <h1 class="mb-6 p-6 text-3xl">Sign Up</h1>

        <form method="POST" action=".">
            <!--django in-built security feature-->
            {% csrf_token %}
            <!--render the form-->
            
            <div class="mb-3">
                <label class="inline-block mb-2">Username:</label><br>{{ form.username}}<br>
                <label class="inline-block mb-2">e-mail:</label><br>{{ form.email}}<br>
                <label class="inline-block mb-2">Enter password:</label><br>{{ form.password1}}<br>
                <label class="inline-block mb-2">Re-enter password:</label><br>{{ form.password2}}<br>
            </div>
            <!--handle errors-->
            {% if form.errors or form.non_field_errors %}
                <div class= "mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{form.non_field_errors}}
                </div>
            {% endif %}
            
            <!--submit button-->
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</form>

        </form>
    </div>
{%endblock%}