puddle/conversation/urls.py
from django.urls import path

from .views import new_conversation, inbox, detail

app_name = "conversation"

urlpatterns = [
    path('new/<int:item_pk>/', new_conversation, name="new"),
    path('inbox/', inbox, name="inbox"),
    path('<int:pk>/', detail, name="detail"),
]

puddle/core/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views 
from . import views
from .forms import LoginForm
app_name = 'core'

urlpatterns = [
    path('',views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    #using django's login view
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout')
]

puddle/item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

puddle/puddle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('conversation/', include('conversation.urls')),
    
    
   
] 


urlpatterns +=   static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

puddle/item/models.py
from django.db import models
from django.contrib.auth.models import User

from django.db.models.signals import pre_delete
from django.dispatch import receiver
import os
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name
    
class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)

    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images',height_field=None, width_field=None, max_length=100)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
@receiver(pre_delete, sender=Item)
def item_pre_delete(sender, instance, **kwargs):
    # Delete the image file from the filesystem
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)

puddle/item/forms.py
from django import forms
from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category','name','description','price','image')
        #for styling
        widgets = {
            'category' : forms.Select(attrs={
            'class' : INPUT_CLASSES
            }),
            'name' : forms.TextInput(attrs={
            'class' : INPUT_CLASSES
            }),
            'description' : forms.Textarea(attrs={
            'class' : INPUT_CLASSES
            }),
            'price' : forms.TextInput(attrs={
            'class' : INPUT_CLASSES
            }),
            'image' : forms.FileInput(attrs={
            'class' : INPUT_CLASSES
            })
        }



class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name','description','price','image','is_sold')
        #for styling
        widgets = {
            
            'name' : forms.TextInput(attrs={
            'class' : INPUT_CLASSES
            }),
            'description' : forms.Textarea(attrs={
            'class' : INPUT_CLASSES
            }),
            'price' : forms.TextInput(attrs={
            'class' : INPUT_CLASSES
            }),
            'image' : forms.FileInput(attrs={
            'class' : INPUT_CLASSES
            }),
            
        }

puddle/item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from django.db.models import Q

from .models import Category,Item
from .forms import NewItemForm, EditItemForm

# Create your views here.

def items(request):
    items = Item.objects.filter(is_sold = False)
    category_id = request.GET.get('category',0)
    
   
    categories = Category.objects.all()
    
    query = request.GET.get('query','')

    if category_id:
        items = items.filter(category_id=category_id)
    #search bar query handling
    if query:
        items = items.filter(Q(name__icontains = query) | Q(description__icontains=query))

    context = {
        'items' : items,
        'query' : query,
        'categories' : categories,
        'category_id' : int(category_id),
    }
    return render(request, 'item/items.html',context)

def detail(request,pk):
    #get requested item with its pk
    item = get_object_or_404(Item, pk=pk)
    #to display related items 
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=item.pk)[0:3]
    context = {
        'item' : item,
        'related_items': related_items
    }

    return render(request,'item/detail.html',context)

@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            return redirect('item:detail', pk=item.id)
        else:
            # Handle the case when the form is not valid
            context = {
                'form': form,
                'title': 'New item',
            }
            return render(request, 'item/form.html', context)
    else:
        form = NewItemForm()
        
    context = {
        'form': form,
        'title': 'New item',
    }
    return render(request, 'item/form.html', context)

#to delete an item from sale (dashboard)
@login_required
def delete(request,pk):
    item = get_object_or_404(Item, pk=pk, created_by = request.user)
    item.delete()

    return redirect('dashboard:index')


@login_required
def edit(request,pk):

    item = get_object_or_404(Item, pk=pk, created_by = request.user)

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES,instance=item)

        if form.is_valid():
            form.save()
            return redirect('item:detail', pk=item.id)
        else:
            # Handle the case when the form is not valid
            context = {
                'form': form,
                'title': 'Edit item',
            }
            return render(request, 'item/form.html', context)
    else:
        form = EditItemForm(instance=item)
        
    context = {
        'form': form,
        'title': 'Edit item',
    }
    return render(request, 'item/form.html', context)

puddle/item/templates/item/detail.html
{% extends 'core/base.html' %}

{%block title%}{{item.name}}{%endblock%}
{%block content%}
    <div class = "grid grid-cols-5 gap-6">
        <div class = "col-span-3">
            
            <img src= "{{item.image.url}}" alt="Item image" class= "rounded-xl">
            
        </div>

        <div class= "col-span-2 p-6 bg-gray-100 rounded-xl">
            <h1 class= "mb-6 text-3xl">{{item.name}}</h1>
            <p class= "text-gray-500"><strong>Price:</strong> {{item.price}}</p>
            <p class= "text-gray-500"><strong>Seller:</strong> {{item.created_by.username}}</p>
            
            {% if item.description %}
                <p class= "text-gray-700">
                    <strong class="text-gray-700">Description:</strong><br>
                {{item.description}}
                </p>
            {% endif %}

            {% if request.user == item.created_by %}
                    <a href= "{% url 'item:edit' item.id %}" class= "inline-block mt-6 px-6 py-3 text-lg font-semibold bg-green-500 hover:bg-green-700 rounded-xl">Edit  </a>

                    <a href= "{% url 'item:delete' item.id %}" class= "inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 hover:bg-red-700 rounded-xl">Delete </a>
                
            

            <br>
            {% else %}
                <a href= "{% url 'conversation:new' item.id%}" class= "inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 hover:bg-teal-700 rounded-xl">Contact seller</a>
            {% endif %}
        </div>
    </div>
<!--display products of same category-->
    <div class = "mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Similar items</h2>
        <!--display similar unsold items-->
        <div class = "grid grid-cols-3 gap-3">
        {%for item in related_items%}
            <div>
                <a href="{% url 'item:detail' item.id %}">
                    <div> <img src="{{item.image.url}}" class = "rounded-xl"> </div>
                </a>  
        <!--Display name and price of item-->
        <div class="p-6 bg-gray-200 rounded-b-xl"> 
            <h2 class= "text-2xl">{{item.name}}</h2>
            <p class= "text-gray-500">Price:{{item.price}}</p> 
        </div>
    </div>
        {%endfor%}
        </div>
    </div>
{%endblock%}

puddle/item/templates/item/form.html
<!--THIS PAGE IS A FORM TO GET NEW ITEM DETAILS FROM USER -->

{% extends 'core/base.html' %}

{%block title%}{{title}}{%endblock%}

{%block content%} 

<h1 class="mb-6 text-3xl">{{title}}</h1>
<form method="post" action="." enctype="multipart/form-data"> <!--enctype is needed to be able to upload images-->
    {% csrf_token %}

    <div class="space-y-4">
        {{form.as_p}}
    </div>

    <!--handle errors-->
    {% if form.errors or form.non_field_errors %}
    <div class= "mb-3 p-6 bg-red-100 rounded-xl">
        {% for field in form %}
            {{ field.errors }}
        {% endfor %}
        {{form.non_field_errors}}
    </div>
{% endif %}
<!--submit button-->
            <button class="mt-4 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</form>
</form>

{%endblock%}

puddle/item/templates/item/items.html
{% extends 'core/base.html' %}
{%block title%}{%endblock%}

{% block content%}
    <div class="grid grid-cols-4 pb-6 gap-4 bg-gray-100">
        <div class="cols-spa-1 mt-3 mx-3">
            <form method='get' action="{% url 'item:items' %}">

                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{query}}" placeholder="Enter item">
                <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button> 
            </form>
            <hr class = "my-6">
            <p class= "font-semibold">Categories</p>
            <ul>
                <ul>
                    {% for category in categories %}
                        <li class="py-2 px-2 rounded-xl {% if category.id == category_id %}bg-gray-300{% endif %}">
                            <a href="{% url 'item:items'%}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                        </li>
                    {% endfor %}
                    </ul>

                    <hr class = "my-6">
                    <p class= "font-semibold">Clear filters</p>

                    <ul>
                        <li><a href="{% url 'item:items' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a></li>
                    

        </div>
        <div class="col-span-3">
            <!--display Newest unsold items-->
            <div class = "grid grid-cols-3 gap-3 mt-3">
                {%for item in items%}
                    <div>
                        <a href="{% url 'item:detail' item.id %}">
                            <div> <img src="{{item.image.url}}" class = "rounded-xl"> </div>
                        </a>  
                <!--Display name and price of item-->
                <div class="p-6 bg-gray-200 rounded-b-xl"> 
                    <h2 class= "text-2xl">{{item.name}}</h2>
                    <p class= "text-gray-500">Price:{{item.price}}</p> 
                </div>
            </div>
                {%endfor%}
                </div>
            </div>
        </div>
    </div>
{% endblock%}